name: Build And Deploy Image

#on:
#  push:
#    branches:
#      - main
#      - staging
# #   pull_request:
# #     branches:
# #       - main
# #       - staging
# 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.ref == 'refs/heads/staging' && secrets.AWS_ACCESS_KEY_ID_STAGING || github.ref == 'refs/heads/main' && secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.ref == 'refs/heads/staging' && secrets.AWS_SECRET_ACCESS_KEY_STAGING || github.ref == 'refs/heads/main' && secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t disbursement-middleware:${{ github.run_number }} .
      - name: Tag Docker image
        run: |
          docker tag disbursement-middleware:${{ github.run_number }} ${{ github.ref == 'refs/heads/staging' && secrets.AWS_ACCOUNT_ID_STAGING  || github.ref == 'refs/heads/main' && secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/disbursement-middleware:${{ github.run_number }}
      - name: Push Docker image to ECR
        run: |
          docker push ${{ github.ref == 'refs/heads/staging' && secrets.AWS_ACCOUNT_ID_STAGING  || github.ref == 'refs/heads/main' && secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/disbursement-middleware:${{ github.run_number }}
      
